// <auto-generated />
namespace AlltBokatWebAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _888 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_888));
        
        string IMigrationMetadata.Id
        {
            get { return "201705091533270_888"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
